### ISSUE TITLE
/docs should point to the latest released version of the doc

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#1]
As titled.

**Comment by lmammino** [comment]
That is actually a very good idea, it will make exploring the documentation easier while browsing the website.

**Option 1**: I would keep `/docs` as a valid URL though (just because it's easier to link anywhere), so if that's ok for you I would just create a redirect from `/docs` to `/docs/master` in the S3 bucket config.

**Option 2**: Anyway, if by *latest released version*, you don't mean `master` but whatever is the latest release (eg. `0.23.x`), then we should do thing differently. It would probably just be easier to change the link in the menu to a dynamic link. In this last case I would still keep the `/docs` index with the list of available versions, so to have a stable URL that we can link everywhere (it just wouldn't be the first thing you'll see if you click in the *docs* link in the menu).

**Comment by mcollina** [comment]
I mean *whatever is the latest release*, e.g. `0.23.x`.

**Comment by lmammino** [comment]
Cool, then I will go with option 2
