### ISSUE TITLE
Anchors being stripped from internal links

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#224]
Originally reported by @salesh: https://github.com/fastify/fastify/issues/2812

> This basically is not working for every page where there is a link to another .md file with an anchor for that file.
> Because the way how the website is built https://github.com/fastify/website
> 
> ```
> Refer to [`ajv options`](Server.md#ajv) to check plugins format
> ```
> 
> Anchor disappear from a link on the building website from Markdown with Metalsmith so it will be like this
> 
> ```
> <p>Refer to <a href=/docs/v3.11.x/Server><code>ajv options</code></a> to check plugins format</p>
> ```
> 
> I believe that this has something with Metalsmith/Markup https://github.com/github/markup/blob/master/README.md#github-markup
> filtering/sanitizing stuff.
> 
> Couldn't find some solution for this I will try to look for something more...

**Comment by salesh** [comment]
Hey @lmammino so I found out about https://github.com/fastify/website/blob/616eb8c988d2c8a905c938839c91a725e9b87bbc/src/scripts/processReleases.js#L144

```
  const relativeLinks = /\((.\/)?(([a-zA-Z0-9\-_]+).md(#[a-z0-9\-_]+)?)\)/gi

    .replace(relativeLinks, (match, ...parts) => `(/docs/${item.version}/${parts[2]})`)
```
The problem is with the parts index.
So the issue is that ${parts[2]} is only ```Server.md``` while ${parts[1]} ->  ```Server.md#ajv``` parts[3] -> ```#ajv```

So should I add ${parts[1]} instead of ${parts[2]} or you want something like ${parts[2]}${parts[3]} ?

**Comment by lmammino** [comment]
Yes @salesh, that seems to be the part of the code responsible for remapping various kind of links that work on GitHub to links that work on the website.

It is a bit messy having to deal with remapping REGEXes but I couldn't figure out any better solution, TBH. If you happen to think of a better approach I am all ears :)

Anyway, I think that appending `parts[3]` might just work for now. 

```javascript
  replace(relativeLinks, (match, ...parts) => `(/docs/${item.version}/${parts[2]}${parts[3]})`)
```

Do you want to test this and maybe submit a PR? If not I should be able to check this one out tomorrow (hopefully)...

**Comment by salesh** [comment]
I understand. :D It was really funny to find out about this function because I was confused about how anchors keep disappearing.
So I did learn a lot in this process of researching. Honestly, nothing comes to my mind at the moment, I was quite delighted with the solution as it is written - so I am not sure if something can be done differently without too much code or without introducing complexity...I can think about it and if something occurs to me I would be glad to ping you :)
