### ISSUE TITLE
set up the domain

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#8]
Can you give me the IP addresses for the A level domain and/or for the CNAME?

**Comment by lmammino** [comment]
We will get a cname once the new s3 bucket is setup. 

If i remember correctly, you told me you can provide a new one so that we can use an officially owned one. 

If that's correct, i can send you by email all the instructions i generally use to create a dedicated aws user with a very restrictive policy for the ci and the s3 bucket configuration needed to expose the content of the bucket as a website.

When that is done you'll have a cname so you can map the dns and i should be able to take care of all the remaining steps.

References #6

**Comment by mcollina** [comment]
Just point me where should I store that config, I'll place it directly there.

**Comment by lmammino** [comment]
@mcollina You have mail ;)

**Comment by mcollina** [comment]
and here we are http://www.fastify.io.

**Comment by lmammino** [comment]
Great stuff @mcollina. I suppose we should also close #6
